### PR TITLE
Compiling with hmatrix (>= 0.17) to fix #7

### LINKED ISSUE #7: Compiling with hmatrix (>= 0.17)
I was trying to update my work environment to a newer one (`stack lts-6.10`), when I noticed that `hnetcdf-0.3` is [unavailable on stack snapshots](https://www.stackage.org/package/hnetcdf). I attempted a [fix](https://github.com/kkats/hnetcdf/tree/katsfix1), which is quick and dirty. 

The main problem seems to be; to work with [hmatrix](https://hackage.haskell.org/package/hmatrix), `CShort`, `CFloat`, and `CDouble` need to be in [`Element`](https://hackage.haskell.org/package/hmatrix-0.17.0.2/src/src/Internal/Matrix.hs) class, which is now hidden.

My [workaround](https://github.com/kkats/hnetcdf/blob/katsfix1/Data/NetCDF/Storable.hs) for `CFloat` and `CDouble` is messy but works. I have no solution for `CShort` and naively assumed that `CShort` and `CInt` are the same thing! I think the way forward includes
- Request `hmatrx` to include `CFloat` etc. in the `Element` class.
- Drop support for `hmatrix`
- Totally different implementation in `hnetcdf`?

Fortunately (?), I do not use `hmatrix` interface with NetCDF, but I really need `hnetcdf` so if there is something I could contribute, let me know. Thanks for creating this package.

### PR DESCRIPTION
**Pull request by kkats**
Thanks @guaraqe for quick reply and testing.

Having a second look at `Data/NetCDF/HMatrix.hs`, it seems to me that the only reason we need `Element` and `Container Vector` classes is to be able to apply `cmap` to `Numeric.LinearAlgebra.Vector` and `Numeric.LinearAlgebra.Matrix`. I found a way around using `Numeric.LinearAlgebra.Devel.mapVectorWithIndex`. Once the mapping is enabled, we can convert `CFloat/CDouble` to `Float/Double` right away. This is not smart, but works...

### CODE REVIEW

**Comment by kkats** [comment]
The previous patch did not fix travis and tests under `test/`. This version, however, fails in `test/test-hmatrix.hs`. The reason is `hmatrix` does not support to `flatten` a `CDouble` matrix -- `CDouble` is not in `Element` class. Now I totally agree with  @guaraqe there is not much we can do but to request `hmatrix` to support `CFloat/CDouble`, to drop support for `hmatrix`, or to rewrite `hmatrix` interface. Maybe this pull-request is not worth merging.

**Comment by guaraqe** [comment]
Is the problem only in the tests module? If the problem is only `CDouble`I can take a look tomorrow.

**Comment by kkats** [comment]
No. Any `toForeignPtr` action to `HMatrix` invokes `hmatrix-0.17.0.2/src/Internal/flatten` which requires `Element` class. I am now wondering if `HMatrix` support be dropped as one can always use [hmatrix-repa](https://github.com/amcphail/hmatrix-repa) and Repa support seems sufficient.

**Comment by ian-ross** [comment]
I think it's going to be impossible to support `hmatrix` properly without changes to `hmatrix` itself.  I think it might be better just to remove support for it from `hnetcdf` for now.

**Comment by ian-ross** [comment]
I'm going to close this since I've removed hmatrix support for the moment.  The solution with `hmatrix-repa` sounds like a good one.

**Pull request closed without merging**
